spring:
  config:
    activate:
      on-profile: local
  jpa:
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        default_batch_fetch_size: 100
  datasource:
    url: jdbc:p6spy:mariadb://flatfra-dev.c1ks6uyqk5sj.ap-northeast-2.rds.amazonaws.com:3306/platfradev
    username: admin
    password: platfradev
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    driver-class-name: org.mariadb.jdbc.Driver
decorator:
  datasource:
    p6spy:
      # 쿼리 찍기 true 운영에서는 false
      enable-logging: false
server:
  port: 8081